### ISSUE TITLE
CuDNN 7 support？

### ISSUE THREAD

**Issue by fuchanghao** [HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-caffe#11]
It seems the Version "cuDNN v7.0.3 (Sept 28, 2017), for CUDA 9.0" shall be the final version of the CuDNN 7.

I tested with waifu2x-caffe it works fine.

Any plan to update it as the waifu2x-caffe did?

**Comment by HolyWu** [comment]
Released r9.
