### ISSUE TITLE
Feature request: Add caffe_library_path and caffe_include_path to meson build options.

### ISSUE THREAD

**Issue by fitu996** [HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-caffe#14]
It will be easier for non-windows users who build customized Caffe library in a custom path. Build customized Caffe library and install it usually conflicts with the already-installed standard Caffe library.

**Comment by HolyWu** [comment]
Hi, please test whether https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-caffe/commit/157c7998801823bc5a6b2c0b41f8bfc6f9fbabc0 works or not.

**Comment by fitu996** [comment]
These options works. Thanks.
