### ISSUE TITLE
Separate waifu2x-caffe as a library

### ISSUE THREAD

**Issue by seadra** [HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-caffe#17]
It would be very useful if you separate the upstream waifu2x-caffe code as a library such that other similar applications can be built upon it.

As far as I know, the upstream doesn't provide a Linux library.

**Comment by HolyWu** [comment]
Sorry, I am not the author of the upstream waifu2x-caffe and hence can't do anything about it. The author does provide an [API](https://github.com/lltcggie/waifu2x-caffe/blob/master/waifu2x-caffe-dll/Source.cpp), however the source code is probably a bit Windows-specific and there is also no build script for non-Windows users.

**Comment by seadra** [comment]
Oh, you misunderstood.

Your repo does compile and run on Linux just fine (there's an [AUR package](https://aur.archlinux.org/packages/vapoursynth-plugin-waifu2x-caffe-git/) for it which makes some slight changes).

What I was asking is, could you bundle everything apart from Waifu2x-caffe.cpp from your repo as a single library? Then you can use that library from Waifu2x-caffe.cpp for your own VapourSynth plugin, and other developers can use it for their own applications as well.

**Comment by HolyWu** [comment]
Ah, I see. I may try it after June as I don't have spare time at the moment.
