### ISSUE TITLE
cuDNN v4 not working on caffe

### ISSUE THREAD

**Issue by chungexcy** [HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-caffe#2]
The latest cuDNN v4 version is not working.

I can run it using cuda without cudnn. But vspipe crashes if I enable cudnn. I tried v4 and v4 rc, but none of them works.

**Comment by HolyWu** [comment]
What platform are you on?

**Comment by chungexcy** [comment]
Windows 8.1 + gtx 960. Caffe-gui has no problem with cudnn on my platform.

**Comment by chungexcy** [comment]
I solved this. My friend gave me his dlls and it works. Thanks.
