### ISSUE TITLE
Python exception: Waifu2x-caffe: only constant format 32-bit float input supported

### ISSUE THREAD

**Issue by YukiSakuma** [HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-caffe#3]
I am just new to vapoursynth and I always get this error whenever loading a video file
![wew](https://cloud.githubusercontent.com/assets/16185735/14051948/6d420de4-f301-11e5-9af4-7c1cb5875fda.jpg)
I am using the portable version x64
and how do you actually output the waifued video file? not just preview

**Comment by HolyWu** [comment]
As the error message said, you must convert the bit depth of the clip to 32-bit first. You can use `core.fmtc.bitdepth(clip, bits=32)` to do the conversion. For outputting, the official documentation at http://www.vapoursynth.com/doc/gettingstarted.html#output-with-vspipe already has an example.

**Comment by YukiSakuma** [comment]
ok I managed to successfully preview the script, but when using VSPIPE
I am getting an error but it outputs yet the video file is like corrupted and the output frames is less than the input, (i.e the input has like 69 frames but the output is only 13 frames)
Here is the code:
`import vapoursynth as vs
import mvsfunc as w
core = vs.get_core()
clip=core.ffms2.Source(source=r"E:\Python35x64\boobiesagain.avi")
clip=core.fmtc.bitdepth(clip, bits=32)
clip=core.caffe.Waifu2x(clip, noise=1, scale=4, block=128, photo=True, cudnn=True, tta=False)
clip.set_output()
`
`
vspipe --y4m wew.vpy - | E:\Downloads\ffmpeg-20160201-git-b62825a-win64-static\ffmpeg-20160201-git-b62825a-win64-static\bin\ffmpeg.exe -i pipe: encoded2.mkv
`
Here what vspipe is saying
![cmd error](https://cloud.githubusercontent.com/assets/16185735/14058837/8680635c-f368-11e5-968a-3dfad6d1374c.jpg)
Here what the output video looks like 
![error](https://cloud.githubusercontent.com/assets/16185735/14058840/89c7fff2-f368-11e5-994f-220f71c655d0.jpg)

**Comment by HolyWu** [comment]
You need to reduce the bit depth to 8 (or 10 if you're encoding in 10-bit) before `clip.set_output()`. Otherwise you are sending 32-bit video to the encoder and are likely to get garbage.

**Comment by YukiSakuma** [comment]
I set the code like this
`import vapoursynth as vs
core = vs.get_core()
clip=core.ffms2.Source(source=r"E:\Python35x64\boobiesagain.avi")
clip=core.fmtc.bitdepth(clip, bits=32)
clip=core.caffe.Waifu2x(clip, noise=1, scale=4, block=128, photo=True, cudnn=True, tta=False)
clip=core.fmtc.bitdepth(clip, bits=8)
clip.set_output()
`
but instead of a total of 69 frames, the total frames output is 68 frames but otherwise I can now watch the output video is there a way to fix the incomplete output frame?

**Comment by HolyWu** [comment]
Well...I'm quite not fond of answering arbitrary questions which have nothing to do with the filter itself. Firstly, VapourSynth itself doesn't have official support for audio. You need to remux the audio stream from the source file with your encoded file. Secondly, it's the encoder(x264 or ffmpeg) to decide what quality(lossy or lossless) the output file will be, not vspipe.

**Comment by YukiSakuma** [comment]
ok thanks I am using ffmpeg when using vspipe so what commands to set it's quality specifically lossless?

**Comment by HolyWu** [comment]
Then you need to consult the documentation of ffmpeg yourself. I don't use ffmpeg for encoding. For x264, the option is `--qp 0`.

**Comment by YukiSakuma** [comment]
Thanks for when using the x264  vspipe can it accept RGB?

**Comment by msg7086** [comment]
http://forum.doom9.org/showthread.php?t=163518

Again, we cannot give much advice about ffmpeg since we simply don't use it. For x264 it accepts RGB input without any problems, though with lower efficiency. YCgCo could be a better choice to preserve RGB color. Again, they are not common practices.
