### ISSUE TITLE
Which Version of cuDNN 5.1 RC?

### ISSUE THREAD

**Issue by fuchanghao** [HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-caffe#6]
It's still not available for cuDNN 5.1 RC for CUDA 8RC.

So Now I have to keep using 
cuDNN v5.1 RC for CUDA 7.5?

https://developer.nvidia.com/rdp/cudnn-download
cuDNN 5.1 RC for CUDA 8RC will be available soon - please check back again.

**Comment by HolyWu** [comment]
Yes, just use cuDNN v5.1 RC for CUDA 7.5 at the moment. It still works fine.
