### ISSUE TITLE
Multi-GPU support?

### ISSUE THREAD

**Issue by SiNNERGi** [HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-caffe#9]
Just a quick question. Does the waifu2x plugin support multiple GPU's or is it only able to utilize one GPU at a time?

**Comment by HolyWu** [comment]
There is a `processor` parameter to let user specify which GPU device to use.

**Comment by SiNNERGi** [comment]
I did not mean selecting which GPU to choose. I was wondering if I could let multiple GPU's work on the same image (or on two separate images from the video) to double the processing speed.

**Comment by HolyWu** [comment]
I guess you may let GPU1 process the even-numbered frames and GPU2 process the odd-numbered frames, and interleave them in the end.

**Comment by SiNNERGi** [comment]
Good idea. Thanks!

**Comment by Nosirus** [comment]
How to do this ? Do you have an example ?

**Comment by 4re** [comment]
```
even = core.std.SelectEvery(core.caffe.Waifu2x(clip, processor=gpu1id), cycle=2, offsets=0)
odd =  core.std.SelectEvery(core.caffe.Waifu2x(clip, processor=gpu2id), cycle=2, offsets=1)
clip = core.std.Interleave([even, odd])
```

**Comment by HolyWu** [comment]
@4re
Out of curiosity, did you try to compile this filter on linux by yourself? Did you encounter any problem? It depends on too many libraries so I really have no clue how to properly write the configure makefile.

**Comment by 4re** [comment]
Not really, I was subscribed to this repo because I was intending to, but it got really complicated and gave up. :/

**Comment by HolyWu** [comment]
No, you don't need to build https://github.com/lltcggie/waifu2x-caffe. I already copied the necessary files to this project and they can be compiled by g++ (at least in mingw64). What you need to build is the [customized Caffe library](https://github.com/lltcggie/caffe), along with all the dependencies: CUDA Toolkit, cuDNN 6, OpenBLAS, Boost, protobuf, glog, gflags, HDF5, and OpenCV. Except CUDA Toolkit and cuDNN, the rest should not be a problem as linux platform is officially supported by the dev. I forked lltcggie's Caffe to [my repo](https://github.com/HolyWu/caffe) which I fixed a compilation error in g++. Do you have a NVIDIA GPU with compute capability >= 3.0 and want to try building it?

**Comment by 4re** [comment]
On my living-room computer it is proving difficult, because atlas requires throttling off on the CPU to be compiled and it looks like everything I try here is useless (most probably something related to the BIOS).

In the coming days I will give a try on another computer I got.

**Comment by HolyWu** [comment]
Um...why choose ATLAS instead of OpenBLAS?

**Comment by 4re** [comment]
Mmh... Because  openblas is not in my distro's main repo. I only got atlas and mkl there and mkl asks you to register at intel and obtain a license.
In the end I think I will go with mkl on this computer.

**Comment by 4re** [comment]
For the caffe on your repo to compile I had to make the following changes:
```diff
diff --git a/Makefile b/Makefile
index 24894062..1e82139f 100644
--- a/Makefile
+++ b/Makefile
@@ -304,15 +304,16 @@ ifdef CUSTOM_CXX
 	CXX := $(CUSTOM_CXX)
 endif
 
-# Static linking
-ifneq (,$(findstring clang++,$(CXX)))
-	STATIC_LINK_COMMAND := -Wl,-force_load $(STATIC_NAME)
-else ifneq (,$(findstring g++,$(CXX)))
-	STATIC_LINK_COMMAND := -Wl,--whole-archive $(STATIC_NAME) -Wl,--no-whole-archive
-else
-  # The following line must not be indented with a tab, since we are not inside a target
-  $(error Cannot static link with the $(CXX) compiler)
-endif
+# This is probably not needed as it looks it's only used for the matlab portion
+# # Static linking
+# ifneq (,$(findstring clang++,$(CXX)))
+# 	STATIC_LINK_COMMAND := -Wl,-force_load $(STATIC_NAME)
+# else ifneq (,$(findstring g++,$(CXX)))
+# 	STATIC_LINK_COMMAND := -Wl,--whole-archive $(STATIC_NAME) -Wl,--no-whole-archive
+# else
+#   # The following line must not be indented with a tab, since we are not inside a target
+#   $(error Cannot static link with the $(CXX) compiler)
+# endif
 
 # Debugging
 ifeq ($(DEBUG), 1)
@@ -370,6 +371,7 @@ ifeq ($(BLAS), mkl)
 else ifeq ($(BLAS), open)
 	# OpenBLAS
 	LIBRARIES += openblas
+	BLAS_INCLUDE += /usr/include/openblas
 else
 	# ATLAS
 	ifeq ($(LINUX), 1)
@@ -403,6 +405,9 @@ LIBRARY_DIRS += $(LIB_BUILD_DIR)
 # Automatic dependency generation (nvcc is handled separately)
 CXXFLAGS += -MMD -MP
 
+# Looks like we have some c++11 code there
+CXXFLAGS += -std=c++11
+
 # Complete build flags.
 COMMON_FLAGS += $(foreach includedir,$(INCLUDE_DIRS),-I$(includedir))
 CXXFLAGS += -pthread -fPIC $(COMMON_FLAGS) $(WARNINGS)
diff --git a/Makefile.config b/Makefile.config
index f6958e60..33c17335 100644
--- a/Makefile.config
+++ b/Makefile.config
@@ -18,14 +18,14 @@ USE_LMDB := 0
 # ALLOW_LMDB_NOLOCK := 1
 
 # Uncomment if you're using OpenCV 3
-# OPENCV_VERSION := 3
+OPENCV_VERSION := 3
 
 # To customize your choice of compiler, uncomment and set the following.
 # N.B. the default for Linux is g++ and the default for OSX is clang++
 # CUSTOM_CXX := g++
 
 # CUDA directory contains bin/ and lib/ directories that we need.
-CUDA_DIR := /usr/local/cuda
+CUDA_DIR := /opt/cuda
 # On Ubuntu 14.04, if cuda tools are installed via
 # "sudo apt-get install nvidia-cuda-toolkit" then use this instead:
 # CUDA_DIR := /usr

```

**Comment by 4re** [comment]
I got it to compile with this changes:
```diff
diff --git a/Makefile b/Makefile
index 24894062..278277b0 100644
--- a/Makefile
+++ b/Makefile
@@ -304,15 +304,16 @@ ifdef CUSTOM_CXX
 	CXX := $(CUSTOM_CXX)
 endif
 
-# Static linking
-ifneq (,$(findstring clang++,$(CXX)))
-	STATIC_LINK_COMMAND := -Wl,-force_load $(STATIC_NAME)
-else ifneq (,$(findstring g++,$(CXX)))
-	STATIC_LINK_COMMAND := -Wl,--whole-archive $(STATIC_NAME) -Wl,--no-whole-archive
-else
-  # The following line must not be indented with a tab, since we are not inside a target
-  $(error Cannot static link with the $(CXX) compiler)
-endif
+# This is probably not needed as it looks it's only used for the matlab portion
+# # Static linking
+# ifneq (,$(findstring clang++,$(CXX)))
+# 	STATIC_LINK_COMMAND := -Wl,-force_load $(STATIC_NAME)
+# else ifneq (,$(findstring g++,$(CXX)))
+# 	STATIC_LINK_COMMAND := -Wl,--whole-archive $(STATIC_NAME) -Wl,--no-whole-archive
+# else
+#   # The following line must not be indented with a tab, since we are not inside a target
+#   $(error Cannot static link with the $(CXX) compiler)
+# endif
 
 # Debugging
 ifeq ($(DEBUG), 1)
@@ -369,7 +370,8 @@ ifeq ($(BLAS), mkl)
 	BLAS_LIB ?= $(MKLROOT)/lib $(MKLROOT)/lib/intel64
 else ifeq ($(BLAS), open)
 	# OpenBLAS
-	LIBRARIES += openblas
+	LIBRARIES += openblas_openmp
+	BLAS_INCLUDE += /usr/include/openblas
 else
 	# ATLAS
 	ifeq ($(LINUX), 1)
@@ -403,6 +405,9 @@ LIBRARY_DIRS += $(LIB_BUILD_DIR)
 # Automatic dependency generation (nvcc is handled separately)
 CXXFLAGS += -MMD -MP
 
+# Looks like we have some c++11 code there
+CXXFLAGS += -std=c++11
+
 # Complete build flags.
 COMMON_FLAGS += $(foreach includedir,$(INCLUDE_DIRS),-I$(includedir))
 CXXFLAGS += -pthread -fPIC $(COMMON_FLAGS) $(WARNINGS)
diff --git a/Makefile.config b/Makefile.config
index f6958e60..33c17335 100644
--- a/Makefile.config
+++ b/Makefile.config
@@ -18,14 +18,14 @@ USE_LMDB := 0
 # ALLOW_LMDB_NOLOCK := 1
 
 # Uncomment if you're using OpenCV 3
-# OPENCV_VERSION := 3
+OPENCV_VERSION := 3
 
 # To customize your choice of compiler, uncomment and set the following.
 # N.B. the default for Linux is g++ and the default for OSX is clang++
 # CUSTOM_CXX := g++
 
 # CUDA directory contains bin/ and lib/ directories that we need.
-CUDA_DIR := /usr/local/cuda
+CUDA_DIR := /opt/cuda
 # On Ubuntu 14.04, if cuda tools are installed via
 # "sudo apt-get install nvidia-cuda-toolkit" then use this instead:
 # CUDA_DIR := /usr
```

**Comment by HolyWu** [comment]
Good. Did you build OpenBLAS with `USE_OPENMP=1`? I think that's not necessary as it has native multi-threading support (using pthread). Anyway, please try the configure script I just commit and see whether it works.

**Comment by 4re** [comment]
Yes, I have that flags set by default on my system, in case somebody does not have it built like that my line will not work for them ofc.
A better option here will be having the old line and a comment explaining the other options, or let `pkg-config` deal with it, but I don't know if this is too much for a `Makefile` file.

The configure script you committed here works good if you make the changes I suggested. Thank you for your efforts, I was not expecting to see this ported to non-windows systems.

**Comment by HolyWu** [comment]
Thank you too for cooperation. Do you actually load it in vsedit and preview it to make sure it works?

**Comment by 4re** [comment]
Yes, it works nicely.
